name: Verificar Página

on:
  schedule:
    - cron: '*/2 * * * *'  # Executa a cada 15 minutos

jobs:
  check-page:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-telegram-bot schedule

    - name: Run script
      run: python meu_script.py
